In [2]:
import numpy as np

In [8]:
temp = np.array([[1,2,3],[4,5,6]])
temp
temp.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
temp.shape

(2, 3)

In [14]:
temp.size

6

In [16]:
temp.ndim

2

In [42]:
t = [[1,2,3],[4,5,6]]
temp[1,1]



5

In [58]:
import random 
arr = np.random.randint(1, 100, (10,5), "% 0.1f%%")
arr

TypeError: data type '% 0.1f%%' not understood

In [74]:
ans = np.array([4,10])+np.array([1,2,3,4])
ans2 = [1,2]+[2,3,4]
ans

ValueError: operands could not be broadcast together with shapes (2,) (4,) 

In [66]:
ans2

[1, 2, 3, 4]

In [70]:
ans2.append(10)

In [77]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

mean = np.mean(arr, axis=0) 
std = np.std(arr, axis = 0) 

normalization = (arr-mean)/std 
print(normalization)

[[-1. -1. -1.]
 [ 1.  1.  1.]]


In [79]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
mean = np.mean(arr, axis=0)  # Mean of each column
std = np.std(arr, axis=0)    # Standard deviation of each column

normalized = (arr - mean) / std
print(normalized)

[[-1. -1. -1.]
 [ 1.  1.  1.]]


In [89]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5])


vec = vec1(np.newaxis)*vec2
vec

TypeError: 'numpy.ndarray' object is not callable

In [2]:
import numpy as np

In [6]:
arr = np.array([7.5, 6. , 2.2, 3.2, 9.3, 4. , 9.1, 9.3, 3.8, 3.7])

In [8]:
arr

array([7.5, 6. , 2.2, 3.2, 9.3, 4. , 9.1, 9.3, 3.8, 3.7])

In [36]:
value = [22,44]

In [44]:
# position = np.random.choice(len(arr),len(value))
position = [2,2]

In [46]:
arr1 = np.insert(arr,position,value)

In [48]:
arr1

array([ 7.5,  6. , 22. , 44. ,  2.2,  3.2,  9.3,  4. ,  9.1,  9.3,  3.8,
        3.7])