In [2]:
import numpy as np

In [8]:
temp = np.array([[1,2,3],[4,5,6]])
temp
temp.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
temp.shape

(2, 3)

In [14]:
temp.size

6

In [16]:
temp.ndim

2

In [42]:
t = [[1,2,3],[4,5,6]]
temp[1,1]



5

In [58]:
import random 
arr = np.random.randint(1, 100, (10,5), "% 0.1f%%")
arr

TypeError: data type '% 0.1f%%' not understood

In [74]:
ans = np.array([4,10])+np.array([1,2,3,4])
ans2 = [1,2]+[2,3,4]
ans

ValueError: operands could not be broadcast together with shapes (2,) (4,) 

In [66]:
ans2

[1, 2, 3, 4]

In [70]:
ans2.append(10)

In [77]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

mean = np.mean(arr, axis=0) 
std = np.std(arr, axis = 0) 

normalization = (arr-mean)/std 
print(normalization)

[[-1. -1. -1.]
 [ 1.  1.  1.]]


In [79]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
mean = np.mean(arr, axis=0)  # Mean of each column
std = np.std(arr, axis=0)    # Standard deviation of each column

normalized = (arr - mean) / std
print(normalized)

[[-1. -1. -1.]
 [ 1.  1.  1.]]


In [89]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5])


vec = vec1(np.newaxis)*vec2
vec

TypeError: 'numpy.ndarray' object is not callable

In [2]:
import numpy as np

In [6]:
arr = np.array([7.5, 6. , 2.2, 3.2, 9.3, 4. , 9.1, 9.3, 3.8, 3.7])

In [8]:
arr

array([7.5, 6. , 2.2, 3.2, 9.3, 4. , 9.1, 9.3, 3.8, 3.7])

In [36]:
value = [22,44]

In [44]:
# position = np.random.choice(len(arr),len(value))
position = [2,2]

In [46]:
arr1 = np.insert(arr,position,value)

In [48]:
arr1

array([ 7.5,  6. , 22. , 44. ,  2.2,  3.2,  9.3,  4. ,  9.1,  9.3,  3.8,
        3.7])

In [26]:
# Input:
arr1 = np.arange(3)
arr2 = np.arange(3,6)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3]).reshape((9))
array_of_arrays
#> array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])], dtype=object)

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [28]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small
#> array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
#>        'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
#>        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
#>        'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
#>        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
#>        'Iris-virginica', 'Iris-virginica', 'Iris-virginica'],
#>       dtype='<U15')

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica'], dtype='<U15')

In [4]:
np.random.seed(10)
a = np.random.randint(20, size=10)
a
#> [ 9  4 15  0 17 16 17  8  9  0]

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [10]:
k = np.argsort(a)
k

array([3, 9, 1, 7, 0, 8, 2, 5, 4, 6], dtype=int64)

In [8]:
for i in range(len(k)):
    print(f"{k[i]}  -->  {a[i]}")

3  -->  9
9  -->  4
1  -->  15
7  -->  0
0  -->  17
8  -->  16
2  -->  17
5  -->  8
4  -->  9
6  -->  0


In [12]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
#> [[ 9  4 15  0 17]
#>  [16 17  8  9  0]]

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [24]:
np.argsort(np.ravel(a)).argsort().reshape(a.shape)

array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]], dtype=int64)

In [34]:
np.max(a)

17

In [36]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
#> array([[9, 9, 4],
#>        [8, 8, 1],
#>        [5, 3, 6],
#>        [3, 3, 3],
#>        [2, 1, 9]])

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [38]:
ma = np.max(a,axis=1)
mi = np.min(a,axis=1)

In [44]:
minbymax = mi/ma
np.around(minbymax, decimals=3)

array([0.444, 0.125, 0.5  , 1.   , 0.111])

In [55]:
np.append(a,minbymax, axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [81]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float')[:,[0,1,2,3]]
iris1 = np.genfromtxt(url, delimiter=',', dtype='object')[:,4]
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [92]:
np.stack((iris,iris1))

ValueError: all input arrays must have the same shape

In [77]:
iris[:,1].sum()

458.1

In [94]:
from io import BytesIO
from PIL import Image
import PIL, requests

# Import image from URL
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

# Read it as Image
I = Image.open(BytesIO(response.content))

# Optionally resize
I = I.resize([150,150])

# Convert to numpy array
arr = np.asarray(I)

# Optionaly Convert it back to an image and show
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)

In [102]:
np.array(r"C:\Users\ASUS\OneDrive\Desktop\linkdine post\Hem.PNG")

array('C:\\Users\\ASUS\\OneDrive\\Desktop\\linkdine post\\Hem.PNG',
      dtype='<U52')

In [114]:
from PIL import Image

In [118]:
img = Image.open(r"C:\Users\ASUS\OneDrive\Desktop\linkdine post\Hem.PNG")

In [124]:
np.array(img).shape

(4032, 3024, 4)

In [128]:
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])

In [136]:
arr[~np.isnan(arr)].astype(int)

array([1, 2, 3, 5, 6, 7])

In [138]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

In [144]:
np.sqrt(np.sum((a-b)**2))

6.708203932499369

In [148]:
np.linalg.norm(a-b)

6.708203932499369

In [150]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

In [156]:
b = b_1d.reshape((len(b_1d),-1))

In [158]:
a_2d-b

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [160]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [162]:
count = 0
for i,k in enumerate(x): 
    if k == 1:
        count +=1
        if count == 5:
            print(i)

8


In [164]:
np.random.seed(100)
Z = np.random.randint(10, size=10)

In [168]:
Z

array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])

In [170]:
ans = []
for i in range(len(Z)-2): 
    ans.append(np.mean(Z[i:i+3]))
ans
    

[6.333333333333333,
 6.0,
 5.666666666666667,
 4.666666666666667,
 3.6666666666666665,
 2.0,
 3.6666666666666665,
 3.0]

In [172]:
np.arange(5,5+10*3 ,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])