In [1]:
import numpy as np 

In [2]:
data = np.array([1,2,3,4,5,6])

In [3]:
type(data)

numpy.ndarray

In [4]:
np.__version__

'1.26.4'

In [5]:
data.shape

(6,)

In [6]:
a = np.array([[[1,2],[2,3],[3,4]],[[1,2],[2,3],[3,4]]])
a.shape

(2, 3, 2)

In [7]:

a.dtype # type of the elements: int32
a.ndim # number of dimensions: 1
a.size # total number of elements: 5
a.itemsize # the size in bytes of each element: 4

4

In [8]:
a.dtype

dtype('int32')

In [9]:
a.ndim

3

In [10]:
a.size

12

In [11]:
a.itemsize

4

In [12]:
print(a)

[[[1 2]
  [2 3]
  [3 4]]

 [[1 2]
  [2 3]
  [3 4]]]


In [13]:
a[0]

array([[1, 2],
       [2, 3],
       [3, 4]])

In [14]:
a[0][0]

array([1, 2])

In [15]:
a[0][0][1]

2

In [16]:
a[0][1:]

array([[2, 3],
       [3, 4]])

In [17]:
lst = [1,2,3,4]

sum(lst)

10

In [18]:
a.sum()

30

In [19]:
a  = a[0]

In [20]:
a

array([[1, 2],
       [2, 3],
       [3, 4]])

In [21]:
a**6

array([[   1,   64],
       [  64,  729],
       [ 729, 4096]], dtype=int32)

In [22]:
a

array([[1, 2],
       [2, 3],
       [3, 4]])

In [23]:
b = np.array([1,2,3,4])
c = np.array([1,2,3,4])

In [24]:
d = np.append(b,c)

In [25]:
d

array([1, 2, 3, 4, 1, 2, 3, 4])

In [26]:
a = np.array([1,2,4])
b = np.array([3,4])
np.dot(a,b)

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)

In [ ]:
from timeit import default_timer as timer

def fib(num): 
    if num == 0:
        return 0 
    elif num ==1:
        return 1 
    else:
        return fib(num-1)+fib(num-2)

start = timer()
lst = []
for i in range(2): 
    lst.append(fib(i))
t1 = end-start

In [39]:
from timeit import default_timer as timer
start = timer()


In [41]:
end = timer()

In [43]:
t1 = end-start

In [45]:
t1

2.7372079999986454

In [55]:
a = np.array([[1,2],[4,5]])
b = np.array([[3,4],[6,8]])


for i in range(len(a[0])):
    for j in range(len(a)): 
        

# c = np.dot(a,b)
c = a*b

c
        

array([[ 3,  8],
       [24, 40]])

In [57]:
a = np.array([1,2])
b = np.array([3,4])
# sum of the products of the corresponding entries
# multiply each corresponding elements and then take the sum
# cumbersome way for lists
dot = 0
for i in range(len(a)):
 dot += a[i] * b[i]
print(dot) # 11
# easy with numpy :)
dot = np.dot(a,b)
print(dot) # 11
# step by step manually
c = a * b
print(c) # [3 8]
d = np.sum(c)
print(d) # 11
# most of these functions are also instance methods
dot = a.dot(b)
print(dot) # 11
dot = (a*b).sum()
print(dot) # 11
# in newer versions
dot = a @ b
print(dot) # 11

11
11
[3 8]
11
11
11
11


In [61]:
from timeit import default_timer as timer
a = np.random.randn(1000)
b = np.random.randn(1000)
A = list(a)
B = list(b)
T = 1000
def dot1():
 dot = 0
 for i in range(len(A)):
     dot += A[i]*B[i]
 return dot
def dot2():
     return np.dot(a,b)
start = timer()
for t in range(T):
 dot1()
end = timer()
t1 = end-start
start = timer()
for t in range(T):
 dot2()
end = timer()
t2 = end-start
print('Time with lists:', t1) # -> 0.19371
print('Time with array:', t2) # -> 0.00112
print('Ratio', t1/t2) 

Time with lists: 0.2646722999998019
Time with array: 0.019432200002484024
Ratio 13.6202951784136


In [ ]:
from timeit import default_timer as timer
a = np.random.randn(1000)
b = np.random.randn(1000)
A = list(a)
B = list(b)

In [ ]:
# list
def dot1():
 dot = 0
 for i in range(len(A)):
     dot += A[i]*B[i]
 return dot

In [ ]:
def dot2():
     return np.dot(a,b)

In [69]:
a = [np.random.randint(100)]

In [73]:
a = np.array(np.random.randint(100))

In [75]:
a

array(84)

In [77]:
a= np.arange(1,100,20)

In [79]:
a

array([ 1, 21, 41, 61, 81])

In [95]:
a = np.array(np.random.rand(1,100))

In [97]:
a

array([[[0.27712287, 0.03568047, 0.32337646, ..., 0.37626683,
         0.55656789, 0.41755899],
        [0.24184682, 0.06344935, 0.46875531, ..., 0.42765494,
         0.0415372 , 0.81255449],
        [0.75738302, 0.80898936, 0.65714457, ..., 0.81318003,
         0.12635713, 0.90790207],
        ...,
        [0.12751569, 0.44624297, 0.04385702, ..., 0.96584741,
         0.35599272, 0.75118972],
        [0.56354281, 0.35815465, 0.88559004, ..., 0.98767666,
         0.14113165, 0.12426931],
        [0.18440653, 0.4125709 , 0.23838883, ..., 0.64471662,
         0.30583773, 0.47932284]]])

In [99]:
a = np.array([[[1,2],[2,3],[3,4]],[[1,2],[2,3],[3,4]]])

In [101]:
a

array([[[1, 2],
        [2, 3],
        [3, 4]],

       [[1, 2],
        [2, 3],
        [3, 4]]])

In [103]:
a[0][0]

array([1, 2])

In [109]:
a[0:2,0,0]

array([1, 1])

In [111]:
a = [[1,2,3],[4,5,6],[7,8,9]]

In [143]:
a[:3][0]

[1, 2, 3]

In [115]:
b = np.array(a)

In [147]:
# b[:3,0]
b[:3,1]

array([2, 5, 8])

In [131]:
b[0][0]

1

In [167]:
d = b.reshape(1,0)
d

ValueError: cannot reshape array of size 9 into shape (1,0)

In [177]:
a = np.array([1,2,3,4,5,6,7,8])
d = a.reshape((2,2,2))
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [225]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
y = np.array([[2,2,2],[1,1,1]])

In [227]:
z = y+x

ValueError: operands could not be broadcast together with shapes (2,3) (4,3) 

In [203]:
z

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])