In [2]:
import numpy as np

In [51]:
# arr = np.arange(1,10).reshape(3,3)
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr1 = np.random.randint(1,10,(3,3))
arr1

array([[6, 4, 3],
       [6, 7, 5],
       [8, 4, 7]])

In [93]:
arr2 = np.eye(3)
arr2

TypeError: 'type' object cannot be interpreted as an integer

In [99]:
arr3 = np.linspace(0,50,5)
arr3

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [ ]:
12.5

In [4]:
# Boolean indexing:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
# [[1 2]
# [3 4]
# [5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [6]:
# same shape with True or False for the condition
bool_idx = a > 2
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [8]:
# note: this will be a rank 1 array!
print(a[bool_idx]) # [3 4 5 6]

[3 4 5 6]


In [1]:
# We can do all of the above in a single concise statement:
print(a[a > 2]) # [3 4 5 6]
# np.where(): same size with modified values
b = np.where(a>2, a, -1)
print(b)
# [[-1 -1]
# [ 3 4]
# [ 5 6]]
# fancy indexing: access multiple indices at once
a = np.array([10,19,30,41,50,61])
b = a[[1,3,5]]
print(b) # [19 41 61]
# compute indices where condition is True
even = np.argwhere(a%2==0).flatten()
print(even) # [0 2 4]
a_even = a[even]
print(a_even) # [10 30 50]

NameError: name 'a' is not defined

In [4]:
a1 = np.array([1,2,3])
a2 = np.array([[9],[8],[7]])

print(a1+a2)
print(a2+a1)

[[10 11 12]
 [ 9 10 11]
 [ 8  9 10]]
[[10 11 12]
 [ 9 10 11]
 [ 8  9 10]]


In [24]:
a = np.array([1,2,3,4,5])
len(a) * a.itemsize

20

In [26]:
'''[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]'''

'[1, 1, 1, 1],\n       [1, 0, 0, 1],\n       [1, 0, 0, 1],\n       [1, 1, 1, 1]'

In [28]:
a = [[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]]
a

[[1, 1, 1, 1], [1, 0, 0, 1], [1, 0, 0, 1], [1, 1, 1, 1]]

In [42]:
a = [[1,2,3,4,5,6,7,8],[4, 5,6,7,4,10]]
a

[[1, 2, 3, 4, 5, 6, 7, 8], [4, 5, 6, 7, 4, 10]]

In [48]:
arr = np.ones((4,4),int)

In [50]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [54]:
arr[3] = 0

In [56]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 0]])

In [58]:
arr[0] = 0

In [60]:
arr

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 0]])

In [76]:
arr[:,0] = 0

In [78]:
arr

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 0]])

In [70]:
arr[:,3] = 0

In [72]:
arr[:][3]

array([0, 0, 0, 0])

In [102]:
a = np.random.rand(16).reshape(4,4)

a

array([[0.81279691, 0.86786265, 0.07134227, 0.8846022 ],
       [0.89535449, 0.51216616, 0.89820667, 0.45758968],
       [0.51579446, 0.32958743, 0.44570515, 0.68398355],
       [0.27950014, 0.23148965, 0.12160894, 0.79699605]])

In [104]:
lst = [[0.81279691, 0.86786265, 0.07134227, 0.8846022 ],
       [0.89535449, 0.51216616, 0.89820667, 0.45758968],
       [0.51579446, 0.32958743, 0.44570515, 0.68398355],
       [0.27950014, 0.23148965, 0.12160894, 0.79699605]]

In [114]:
a[:,3]

array([0.8846022 , 0.45758968, 0.68398355, 0.79699605])

In [106]:
lst

[[0.81279691, 0.86786265, 0.07134227, 0.8846022],
 [0.89535449, 0.51216616, 0.89820667, 0.45758968],
 [0.51579446, 0.32958743, 0.44570515, 0.68398355],
 [0.27950014, 0.23148965, 0.12160894, 0.79699605]]

[0.81279691, 0.86786265, 0.07134227, 0.8846022]

In [ ]:

temp = -inf
print(temp)

In [3]:
mat = []
flag = True
for i in range(8):
    temp = []
    for j in range(8):
        if flag:
            if j % 2 == 0:
                temp.append(1)
            else:
                temp.append(0)
        else:
            if j % 2 == 0:
                temp.append(0)
            else:
                temp.append(1)
    mat.append(temp)
    if flag:
        flag = False
    else:
        flag = True
mat
        

[[1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1]]

In [1]:
import numpy as np

In [7]:
a = np.random.randint(1,100,25).reshape(5,5)
a
# for i in np.nditer(a):
#     print(i)

array([[29, 41, 85, 48, 14],
       [ 9, 84, 26, 43, 80],
       [38, 72, 42, 94, 59],
       [32, 37, 60, 29, 73],
       [84,  7, 15, 13, 46]])

In [9]:
np.ravel(a)

array([29, 41, 85, 48, 14,  9, 84, 26, 43, 80, 38, 72, 42, 94, 59, 32, 37,
       60, 29, 73, 84,  7, 15, 13, 46])

In [16]:
np.transpose(a)

array([[29,  9, 38, 32, 84],
       [41, 84, 72, 37,  7],
       [85, 26, 42, 60, 15],
       [48, 43, 94, 29, 13],
       [14, 80, 59, 73, 46]])

In [22]:
a1 = a.transpose()

In [30]:
np.stack((a,a1))

array([[[29, 41, 85, 48, 14],
        [ 9, 84, 26, 43, 80],
        [38, 72, 42, 94, 59],
        [32, 37, 60, 29, 73],
        [84,  7, 15, 13, 46]],

       [[29,  9, 38, 32, 84],
        [41, 84, 72, 37,  7],
        [85, 26, 42, 60, 15],
        [48, 43, 94, 29, 13],
        [14, 80, 59, 73, 46]]])

In [32]:
np.hstack((a,a1))

array([[29, 41, 85, 48, 14, 29,  9, 38, 32, 84],
       [ 9, 84, 26, 43, 80, 41, 84, 72, 37,  7],
       [38, 72, 42, 94, 59, 85, 26, 42, 60, 15],
       [32, 37, 60, 29, 73, 48, 43, 94, 29, 13],
       [84,  7, 15, 13, 46, 14, 80, 59, 73, 46]])

In [54]:
np.hsplit((a),2.5)

[array([[29, 41, 85],
        [ 9, 84, 26],
        [38, 72, 42],
        [32, 37, 60],
        [84,  7, 15]]),
 array([[48, 14],
        [43, 80],
        [94, 59],
        [29, 73],
        [13, 46]])]

In [56]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [60]:
np.random.uniform(1,10,5)

array([8.23721864, 7.14601316, 8.1265803 , 5.02069623, 9.1554725 ])

In [3]:
import numpy as np

In [47]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [49]:
np.random.rand(5)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])