In [2]:
import numpy as np

How to stack two arrays vertically?
Difficulty Level: L2

Q. Stack arrays a and b vertically

Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
Desired Output:

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

In [13]:
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)
print(a,b)

[[0 1 2 3 4]
 [5 6 7 8 9]] [[1 1 1 1 1]
 [1 1 1 1 1]]


In [27]:
ans = np.hstack((a,b))
ans

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10. How to generate custom sequences in numpy without hardcoding?
Difficulty Level: L2

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])`
Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [48]:
a = np.array([1,2,3])

In [54]:
ab = np.repeat(a,3)
a = np.hstack((a,a,a))
np.hstack((ab,a))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [66]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

11. How to get the common items between two python numpy arrays?
Difficulty Level: L2

Q. Get the common items between a and b

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
Desired Output:

array([2, 4])

In [73]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [75]:
np.intersect1d(a,b)

array([2, 4])

12. How to remove from one array those items that exist in another?
Difficulty Level: L2

Q. From array a remove all items present in array b

Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
Desired Output:

array([1,2,3,4])

In [78]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [84]:
np.where(b in a , a,0)

array([0, 0, 0, 0, 0])

In [92]:
a[~np.isin(a,b)]

array([1, 2, 3, 4])

In [94]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

13. How to get the positions where elements of two arrays match?
Difficulty Level: L2

Q. Get the positions where elements of a and b match

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
Desired Output:

#> (array([1, 3, 5, 7]),)

In [119]:
a = np.array([1,2,3,2,3,4,0,4,9,6])
b = np.array([7,2,10,2,7,4,9,4,9,4])

In [129]:
# a[np.isin(a,b),np.argwhere()] 

In [123]:
np.where(a==b)

(array([1, 3, 5, 7, 8], dtype=int64),)

14. How to extract all numbers between a given range from a numpy array?
Difficulty Level: L2

Q. Get all items between 5 and 10 from a.

Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])
Desired Output:

(array([6, 9, 10]),)

In [132]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [142]:
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

In [154]:
inx = np.where((a>=5) & (a<=10))

In [156]:
a[inx]

array([ 6,  9, 10])

15. How to make a python function that handles scalars to work on numpy arrays?
Difficulty Level: L2

Q. Convert the function maxx that works on two scalars, to work on two arrays.

Input:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5
Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [201]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

In [203]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [205]:
[maxx(a[i],b[i]) for i in range(len(a))] 

[6, 7, 9, 8, 9, 7, 5]

In [221]:
temp = np.vectorize(maxx)
temp(a,b)

array([6, 7, 9, 8, 9, 7, 5])

16. How to swap two columns in a 2d numpy array?
Difficulty Level: L2

Q. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
arr

In [229]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [231]:
arr[:,[2,1,0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

17. How to swap two rows in a 2d numpy array?
Difficulty Level: L2

Q. Swap rows 1 and 2 in the array arr:

arr = np.arange(9).reshape(3,3)
arr

In [234]:
arr[[2,0,1],:]

array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

18. How to reverse the rows of a 2D array?
Difficulty Level: L2

Q. Reverse the rows of a 2D array arr.

# Input
arr = np.arange(9).reshape(3,3)

In [237]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [249]:
arr[::-1,::-1]

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

19. How to reverse the columns of a 2D array?
Difficulty Level: L2

Q. Reverse the columns of a 2D array arr.

# Input
arr = np.arange(9).reshape(3,3)

20. How to create a 2D array containing random floats between 5 and 10?
Difficulty Level: L2

Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

np.random.randint(5,10,(5,3))+np.random.rand(15).reshape(5,3)

In [255]:
np.random.uniform(5,10,(5,3))

array([[8.5543193 , 9.79218233, 8.90964671],
       [6.04802509, 5.18829537, 5.19139775],
       [5.31082766, 8.34024726, 5.4352841 ],
       [5.33522886, 5.52460921, 5.16812949],
       [5.03390081, 7.46521988, 9.88848098]])

In [267]:
r = np.random.random(10)

In [269]:
r

array([0.24801897, 0.10470792, 0.4098855 , 0.2341138 , 0.45174137,
       0.50340114, 0.90022968, 0.11186356, 0.08250902, 0.04405448])

In [281]:
lst = ["{:.2f}".format(val) for val in r]
lst

['0.25',
 '0.10',
 '0.41',
 '0.23',
 '0.45',
 '0.50',
 '0.90',
 '0.11',
 '0.08',
 '0.04']

22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
Difficulty Level: L1

Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

Input:

# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

#> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
#>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
#>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])
Desired Output:

#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])

In [3]:
import numpy as np

In [4]:
arr = np.random.random([3,3])/1e3
arr

array([[4.77324836e-04, 6.66005632e-04, 9.49090937e-04],
       [4.77688937e-04, 6.78278347e-04, 4.58112733e-04],
       [5.55340985e-04, 2.16405574e-06, 9.95903098e-04]])

In [17]:
np.around(arr, decimals=6)

array([[7.25e-04, 9.17e-04, 5.48e-04],
       [8.58e-04, 4.10e-05, 1.74e-04],
       [2.97e-04, 5.79e-04, 4.98e-04]])

In [19]:
# np.set_printoptions(suppress=True, precision=8)
arr

array([[7.24632295e-04, 9.16540190e-04, 5.48487791e-04],
       [8.58450068e-04, 4.07921249e-05, 1.74402777e-04],
       [2.97203644e-04, 5.79079552e-04, 4.97526624e-04]])

In [ ]:
np.set_printoptions()

25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
Difficulty Level: L2

Q. Import the iris dataset keeping the text intact.

In [39]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
s = ['A','B','C','D','Category ']
arr = np.genfromtxt(url,delimiter=',', names=s)

df = pd.DataFrame(arr)
df

A    B    C    D  Category
0    5.1  3.5  1.4  0.2       NaN
1    4.9  3.0  1.4  0.2       NaN
2    4.7  3.2  1.3  0.2       NaN
3    4.6  3.1  1.5  0.2       NaN
4    5.0  3.6  1.4  0.2       NaN
..   ...  ...  ...  ...       ...
145  6.7  3.0  5.2  2.3       NaN
146  6.3  2.5  5.0  1.9       NaN
147  6.5  3.0  5.2  2.0       NaN
148  6.2  3.4  5.4  2.3       NaN
149  5.9  3.0  5.1  1.8       NaN

[150 rows x 5 columns]

In [19]:
import pandas as pd

In [31]:
s = ['A','B','C','D','Category ']
pd.read_csv(url,sep=',', names=s)

A    B    C    D       Category 
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [43]:
arr1 = np.genfromtxt(url,delimiter=',')

In [69]:
a = arr1[:,1]
a

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
       3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 2.6, 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, 3.1, 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. ])

In [77]:
np.quantile(a,[.25,.75])


array([2.8, 3.3])

In [75]:
np.percentile(a,25)

2.8

In [79]:
arr = np.array([10, 20, 30, 40, 50])
values = [99, 88]

In [83]:
position=np.random.choice(len(arr),len(values))
position

array([1, 3])

In [87]:
np.insert(arr,position,values)

array([10, 99, 20, 30, 88, 40, 50])

35. How to drop rows that contain a missing value from a numpy array?

In [4]:
arr = np.array([[1, 2, 3],
                [4, np.nan, 6],
                [7, 8, 9],
                [np.nan, 11, 12]])

In [17]:
arr[~np.isnan(arr).any(axis=1)]

array([[1., 2., 3.],
       [7., 8., 9.]])

In [39]:
arr = np.array([[1, 2],
                [2, 4],
                [3, 9],
                [4, 8]])

In [41]:
np.corrcoef(arr[:,0],arr[:,1])

array([[1.        , 0.89868436],
       [0.89868436, 1.        ]])

In [49]:
co = np.cov(arr[:,0],arr[:,1])
co

array([[ 1.66666667,  3.83333333],
       [ 3.83333333, 10.91666667]])

In [51]:
n = (np.std(arr[:,0])*np.std(arr[:,1]))
n

3.199120973017432

In [47]:
co/n

array([[0.52097644, 1.19824582],
       [1.19824582, 3.4123957 ]])

In [53]:
x = arr[:, 0]
y = arr[:, 1]

# Calculate covariance matrix (2x2)
cov_matrix = np.cov(x, y, bias=False)
cov_xy = cov_matrix[0, 1]

# Calculate standard deviations
std_x = np.std(x, ddof=1)  # ddof=1 for sample std
std_y = np.std(y, ddof=1)

# Calculate correlation
corr = cov_xy / (std_x * std_y)

In [55]:
corr

0.8986843649392479

In [63]:
import numpy as np

# Sample 2D NumPy array
data = np.array([
    [10, 200],
    [15, 24],
    [20, 28],
    [25, 35]
])

# Extract the two columns
col1 = data[:, 0]
col2 = data[:, 1]

# Compute correlation
correlation_matrix = np.corrcoef(col1, col2)

# Print correlation coefficient
print("Correlation coefficient:", correlation_matrix)


Correlation coefficient: [[ 1.         -0.74033235]
 [-0.74033235  1.        ]]


In [65]:
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

In [71]:
unq,count = np.unique(arr,return_counts=True  )

In [75]:
unq

array([1, 2, 3, 4])

In [73]:
count

array([1, 2, 3, 4], dtype=int64)

In [77]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6],
                [7, 8]])

In [87]:
co = np.cov(arr[:,0],arr[:,1])
co = co[0,1]

In [95]:
s = np.std(arr[:,0])
s1 = np.std(arr[:,1])
s1

2.23606797749979

In [97]:
(s*s1)

5.000000000000001

In [99]:
co

6.666666666666666