1. Import numpy as np and see the version
Difficulty Level: L1

Q. Import numpy as np and print the version number.

In [2]:
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.where((a<5) & (8>a),a,-1)

array([ 0,  1,  2,  3,  4, -1, -1, -1, -1, -1])

8. How to stack two arrays vertically?
Difficulty Level: L2

Q. Stack arrays a and b vertically

Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
Desired Output:

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

In [61]:
a = np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
b = np.repeat(1, 10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [65]:
ab = np.stack((a,b))

In [69]:
ab.shape

(2, 2, 5)

In [71]:
ad = np.hstack((a,b))

In [73]:
ad

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [75]:
ad.shape

(2, 10)

10. How to generate custom sequences in numpy without hardcoding?
Difficulty Level: L2

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])`
Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [132]:
a = np.array([1,2,3])

In [144]:
b = np.repeat(a,3)
c = np.hstack((b,a,a,a))

In [146]:
c

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [156]:
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

12. How to remove from one array those items that exist in another?
Difficulty Level: L2

Q. From array a remove all items present in array b

Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
Desired Output:

array([1,2,3,4])

In [159]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [161]:
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Boolean Indexing

In [166]:
arr = np.random.randint(1,20,10)

In [168]:
arr

array([11, 11,  7,  2, 10, 16, 12, 13,  8,  6])

In [206]:
inx = arr[(arr>5) & (10<arr)]
inx

array([11, 11, 16, 12, 13])

In [202]:
np.where((arr>5) & (10<arr))

(array([0, 1, 5, 6, 7], dtype=int64),)

In [204]:
np.where((arr>5) | (10<arr))

(array([0, 1, 2, 4, 5, 6, 7, 8, 9], dtype=int64),)

12. How to remove from one array those items that exist in another?
Difficulty Level: L2

Q. From array a remove all items present in array b

Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
Desired Output:

array([1,2,3,4])

In [209]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [227]:
b[~np.isin(b,a)]

array([6, 7, 8, 9])

13. How to get the positions where elements of two arrays match?
Difficulty Level: L2

Q. Get the positions where elements of a and b match

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
Desired Output:

#> (array([1, 3, 5, 7]),)

In [230]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [240]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [262]:
a = np.array([2, 6, 1,4,5,7, 9, 10, 3, 27])

In [264]:
a

array([ 2,  6,  1,  4,  5,  7,  9, 10,  3, 27])

In [276]:
a[np.where(((a>5) & (10>=a)),True, False)]

array([ 6,  7,  9, 10])

In [280]:
a[(a>5) & (10>=a)]

array([ 6,  7,  9, 10])

In [292]:
np.random.rand(2,3)

array([[0.07364173, 0.41602934, 0.86673246],
       [0.91252471, 0.69705443, 0.02494533]])

In [298]:
np.random.randint(1,10,(2,3))

array([[4, 7, 6],
       [5, 4, 2]])

In [312]:
np.random.uniform(1,10,10)

array([6.11157676, 6.73258771, 3.01209926, 2.95673482, 3.34282194,
       4.78433717, 8.53749583, 5.34245377, 3.25318163, 2.26875909])

In [306]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [308]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
arr = np.random.uniform(1,10,10)

In [328]:
# np.around(arr, decimals=3)

array([5.428, 4.349, 5.77 , 2.673, 7.252, 7.879, 2.113, 9.428, 2.379,
       5.023])

In [28]:
np.set_printoptions(precision=8,suppress=True)
arr

array([7.51705056, 6.01897241, 2.16312444, 3.17914869, 9.31962498,
       3.99476954, 9.09204424, 9.32804255, 3.79187345, 3.66817646])

In [30]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[0.0005434 , 0.00027837, 0.00042452],
       [0.00084478, 0.00000472, 0.00012157],
       [0.00067075, 0.00082585, 0.00013671]])

In [44]:
arr

array([7.51705056, 6.01897241, 2.16312444, 3.17914869, 9.31962498,
       3.99476954, 9.09204424, 9.32804255, 3.79187345, 3.66817646])

In [103]:
np.random.seed(10000000)
np.random.choice(arr)

3.17914868714368

In [105]:
arr

array([7.51705056, 6.01897241, 2.16312444, 3.17914869, 9.31962498,
       3.99476954, 9.09204424, 9.32804255, 3.79187345, 3.66817646])

In [127]:
np.set_printoptions(threshold=6)

In [129]:
arr

array([7.5, 6. , 2.2, ..., 9.3, 3.8, 3.7])

In [135]:
np.set_printoptions(threshold=len(arr))
arr

array([7.5, 6. , 2.2, 3.2, 9.3, 4. , 9.1, 9.3, 3.8, 3.7])

25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
Difficulty Level: L2

Q. Import the iris dataset keeping the text intact.

In [138]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [144]:
import pandas as pd 
df = pd.read_csv(url,delimiter=",")

In [174]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   5.1          149 non-null    float64
 1   3.5          149 non-null    float64
 2   1.4          149 non-null    float64
 3   0.2          149 non-null    float64
 4   Iris-setosa  149 non-null    object 
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [176]:
data = np.genfromtxt(url,delimiter=",",dtype=object)

In [182]:
data[:,3]

array([b'0.2', b'0.2', b'0.2', ..., b'2.0', b'2.3', b'1.8'], dtype=object)

In [184]:
arr

array([7.5, 6. , 2.2, 3.2, 9.3, 4. , 9.1, 9.3, 3.8, 3.7])

In [190]:
position = np.random.choice(arr,2)
position

array([9.3, 9.3])

In [17]:
arr = [(1,2),(3,4),(5,6),(7,8)]
arr = np.array(arr)
arr.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
arr.transpose().reshape(4,2)

array([[1, 3],
       [5, 7],
       [2, 4],
       [6, 8]])

In [7]:
arr[0]

(1, 2)

In [9]:
arr[0][0]

1

In [29]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
data = np.genfromtxt(url, delimiter=',', dtype=object)

In [31]:
data

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4',

In [35]:
data2 = np.array([row.tolist()[:4] for row in data])
data2[:4].shape

(4, 4)

In [37]:
data.shape

(150, 5)

In [51]:
arr = np.array([1,2,3,4,5,6,np.nan,np.nan,7,13])
arr

array([ 1.,  2.,  3.,  4.,  5.,  6., nan, nan,  7., 13.])

In [41]:
np.isnan(arr)

array([False, False, False, False, False, False,  True,  True, False,
       False])

In [71]:
temp = np.where(np.isnan(arr))

In [75]:
arr[temp]

array([nan, nan])

### Filtering 

In [91]:
# boolean filter 

arr = np.random.randint(size = 30, low = 1,high = 100)
arr

array([96, 71, 28, 76, 85, 48, 40, 90, 50, 26, 95, 67, 53,  5, 24, 36, 79,
       27,  3, 51, 96, 96, 23, 50, 51, 93, 19, 86, 36, 13])

In [104]:
data = ~((arr>=50) & (arr<=80))

array([ True, False,  True, False,  True,  True,  True,  True, False,
        True,  True, False, False,  True,  True,  True, False,  True,
        True, False,  True,  True,  True, False, False,  True,  True,
        True,  True,  True])

In [108]:
arr[~((arr>=50) & (arr<=80))]

array([96, 28, 85, 48, 40, 90, 26, 95,  5, 24, 36, 27,  3, 96, 96, 23, 93,
       19, 86, 36, 13])

In [124]:
a = np.where(((arr>=50) & (arr<=80)),0,arr)
a

array([96,  0, 28,  0, 85, 48, 40, 90,  0, 26, 95,  0,  0,  5, 24, 36,  0,
       27,  3,  0, 96, 96, 23,  0,  0, 93, 19, 86, 36, 13])

33. How to find the position of missing values in numpy array?
Difficulty Level: L2

Q. Find the number and position of missing values in iris_2d's sepallength (1st column)

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [137]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
data = np.genfromtxt(url, delimiter=',', dtype='float')
data[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
data

array([[5.1, 3.5, 1.4, 0.2, nan],
       [nan, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan],
       [5.4, 3.9, 1.7, 0.4, nan],
       [4.6, 3.4, 1.4, 0.3, nan],
       [5. , 3.4, 1.5, 0.2, nan],
       [4.4, 2.9, 1.4, 0.2, nan],
       [4.9, 3.1, 1.5, 0.1, nan],
       [5.4, 3.7, 1.5, 0.2, nan],
       [4.8, 3.4, 1.6, 0.2, nan],
       [4.8, 3. , 1.4, 0.1, nan],
       [4.3, nan, 1.1, 0.1, nan],
       [5.8, 4. , 1.2, 0.2, nan],
       [5.7, 4.4, 1.5, 0.4, nan],
       [5.4, 3.9, 1.3, 0.4, nan],
       [5.1, 3.5, 1.4, 0.3, nan],
       [5.7, 3.8, 1.7, nan, nan],
       [5.1, 3.8, 1.5, 0.3, nan],
       [5.4, 3.4, 1.7, 0.2, nan],
       [5.1, 3.7, 1.5, 0.4, nan],
       [4.6, 3.6, 1. , nan, nan],
       [5.1, 3.3, 1.7, 0.5, nan],
       [4.8, 3.4, 1.9, 0.2, nan],
       [5. , 3. , 1.6, 0.2, nan],
       [5. , 3.4, 1.6, 0.4, nan],
       [5.2, 3.5, 1.5, nan, nan],
       [5.2, 3.4, 1.4, 0.2, nan],
       [4.7, 3

In [151]:
data = data[:,:4]
np.isnan(data[:,]).sum()

5

In [173]:
data = data[:,:4]

In [175]:
data

array([[5.1, 3.5, 1.4, 0.2],
       [nan, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, nan, 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, nan],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , nan],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, nan],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, nan, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [nan, 4.2, 1.4, 0.2],
       [4.9, 3

In [203]:
d=  np.where(np.isnan(data))[0]
for i in range(len(data)):
    if i in d:
        np.delete(data,i)
        print(data[i])

[nan 3.  1.4 0.2]
[4.3 nan 1.1 0.1]
[5.7 3.8 1.7 nan]
[4.6 3.6 1.  nan]
[5.2 3.5 1.5 nan]
[4.7 3.2 nan 0.2]
[nan 4.2 1.4 0.2]
[5.5 nan 1.3 0.2]
[nan 3.2 1.3 0.2]
[6.2 2.2 nan 1.5]
[6.1 2.8 nan 1.3]
[nan 2.9 4.3 1.3]
[nan 3.  4.5 nan]
[4.9 nan 4.5 1.7]
[6.4 2.7 5.3 nan]
[6.  3.  4.8 nan]
[6.9 3.1 5.4 nan]
[6.7 3.  5.2 nan]


IndexError: arrays used as indices must be of integer (or boolean) type

In [4]:
import numpy as np

In [8]:
arr = np.empty((4,4))

In [10]:
arr

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        4.67293691e-307],
       [1.11256817e-306, 1.06811422e-306, 1.42417221e-306,
        1.11260619e-306],
       [8.90094053e-307, 1.86919378e-306, 1.06809792e-306,
        1.37962456e-306],
       [1.69111861e-306, 1.78020169e-306, 1.37961777e-306,
        7.56599807e-307]])

In [12]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [14]:
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])

In [17]:
species_out

array(['Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
 

In [20]:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr
#> array([2, 3, 2, 2, 2, 1])

array([2, 3, 2, 2, 2, 1])

In [22]:
name = np.unique(arr)

In [24]:
name

array([1, 2, 3])

In [26]:
def one_hot_en(num):
    if num == 1: 
        return [1,0,0]
    elif num == 2:
        return [0,1,0]
    elif num == 3:
        return [0,0,1]

In [28]:
lst = []
for i in arr:
    lst.append(one_hot_en(i))
    

In [32]:
for i in lst:
    print(i)

[0, 1, 0]
[0, 0, 1]
[0, 1, 0]
[0, 1, 0]
[0, 1, 0]
[1, 0, 0]


In [64]:
np.random.seed(10)
arr = np.random.randint(20, size=10)
print(a)
#> [ 9  4 15  0 17 16 17  8  9  0]

[ 0  0  4  8  9  9 15 16 17 17]


In [62]:
for i , k in enumerate(np.sort(a)):
    print(f"{i} ====> {k}")

0 ====> 0
1 ====> 0
2 ====> 4
3 ====> 8
4 ====> 9
5 ====> 9
6 ====> 15
7 ====> 16
8 ====> 17
9 ====> 17


In [57]:
a.argmin()

0