In [4]:
import numpy as np

In [10]:
np.__version__

'1.26.4'

In [12]:
a = np.array([1,2,3,4,5,6])

In [14]:
a

array([1, 2, 3, 4, 5, 6])

In [16]:
list(a)

[1, 2, 3, 4, 5, 6]

In [18]:
a

array([1, 2, 3, 4, 5, 6])

In [22]:
a.shape

(6,)

In [24]:
a.dtype

dtype('int32')

In [26]:
a.itemsize

4

In [70]:
arr = np.random.uniform(1,10,10)
arr

array([8.306948, 2.356433, 7.37125 , ..., 5.353907, 9.408221, 5.477813])

In [79]:
np.set_printoptions(precision=6)

In [81]:
arr

array([8.306948, 2.356433, 7.37125 , ..., 5.353907, 9.408221, 5.477813])